# Generated by Django 5.1 on 2024-08-15 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Create_Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=150)),
                ('recipe_description', models.TextField()),
                ('recipe_image', models.ImageField(upload_to='recipe-img')),
            ],
        ),
    ]
